/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.9/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
        kotlin("jvm") version "1.9.24" apply false
        kotlin("plugin.serialization") version "1.9.24" apply false
        id("com.ncorti.ktfmt.gradle") version "0.19.0" apply false
}

rootProject.name = "paseto-kotlin"
include("paseto-kotlin-core", "paseto-kotlin-kotlinx")
project(":paseto-kotlin-core").projectDir = file("core")
project(":paseto-kotlin-kotlinx").projectDir = file("kotlinx")
